name: Build & publish to PyPI
on:
  push:                    # run on new version
    tags: ["v*"]     

permissions:
  id-token: write    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }

      - name: Build sdist+wheel
        run: |
          python -m pip install --upgrade build
          python -m build
      - uses: actions/upload-artifact@v4
        with: { name: dist, path: dist/ }

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: pypi      
    permissions: { id-token: write }
    steps:
      - uses: actions/download-artifact@v4
        with: { name: dist, path: dist/ }

      - uses: pypa/gh-action-pypi-publish@release/v1
